steps:
  # Build using Node.js buildpack
  - name: "gcr.io/k8s-skaffold/pack"
    args:
      - build
      - "gcr.io/golaghat-honda-dealer/honda-golaghat-dealer-be"
      - "--builder=gcr.io/buildpacks/builder:v1"
      - "--env=NODE_ENV=production"

  # Push to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/golaghat-honda-dealer/honda-golaghat-dealer-be"]

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "honda-golaghat-dealer-be"
      - "--image=gcr.io/golaghat-honda-dealer/honda-golaghat-dealer-be"
      - "--region=asia-south1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--port=8080"

images:
  - "gcr.io/golaghat-honda-dealer/honda-golaghat-dealer-be"

timeout: 1200s
